次のうち正しい記述はどれですか。
例外処理のコードは通常の処理コードと分離される。
//誤り。try-catchではtryの中に通常の実行分を、catchの中に例外が発生した際の処理を記述する。

例外を明示的に発生させることはできない。
//誤り。業務的な例外は開発者が明示的に発生させる。


例外処理を行う場所を任意に選択することができる。
//正しい。throwsによってメソッドの呼び出し元で例外処理できる。

例外は発生したメソッド内で必ず処理しなければならない。
//誤り。前項参照。

特定の状況に合わせて例外クラスを独自に定義できる。
//誤り。例外的状況を表すクラスがAPIとして定義されている。